apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job: "package"
spec:
  containers:
    - name: jnlp
      image: jenkinsciinfra/packaging:8.0.2
      imagePullPolicy: "IfNotPresent"
      env:
        - name: "HOME"
          value: "/home/jenkins/agent/workspace"
        - name: "JENKINS_JAVA_BIN"
          value: "/opt/jdk-21/bin/java"
        - name: "JENKINS_JAVA_OPTS"
          value: "-XX:+PrintCommandLineFlags"
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
        requests:
          memory: "1Gi"
          cpu: "1"
      securityContext:
        privileged: false
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: data-storage-jenkins-io
          mountPath: /srv/releases/jenkins
          subPath: ./get.jenkins.io/mirrorbits/
        - name: data-storage-jenkins-io
          mountPath: /var/www/pkg.jenkins.io.staging
          subPath: ./pkg.jenkins.io/staging/
  volumes:
    - name: data-storage-jenkins-io
      persistentVolumeClaim:
        claimName: data-storage-jenkins-io
  nodeSelector:
    kubernetes.azure.com/agentpool: releasepool
    kubernetes.io/os: linux
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
    - key: "jenkins"
      operator: "Equal"
      value: "release.ci.jenkins.io"
      effect: "NoSchedule"
