apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job: "package"
spec:
  containers:
    - name: jnlp
      image: jenkinsciinfra/packaging:2.1.9
      imagePullPolicy: "IfNotPresent"
      env:
        - name: "HOME"
          value: "/home/jenkins/agent/workspace"
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
        requests:
          memory: "1Gi"
          cpu: "1"
      securityContext:
        privileged: false
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: binary-core-packages
          mountPath: /srv/releases/jenkins
        - name: website-core-packages
          mountPath: /var/www/pkg.jenkins.io.staging/
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
  volumes:
    - name: binary-core-packages
      persistentVolumeClaim:
        claimName: binary-core-packages
    - name: website-core-packages
      persistentVolumeClaim:
        claimName: website-core-packages
