apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job: "package"
    #Following label is required by the workload identity process https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet#pod-labels
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: release-ci-jenkins-io-agents
  containers:
    - name: jnlp
      image: jenkinsciinfra/packaging:8.2.8
      imagePullPolicy: "IfNotPresent"
      env:
        - name: "JENKINS_JAVA_BIN"
          value: "/opt/jdk-21/bin/java"
        - name: "JENKINS_JAVA_OPTS"
          value: "-XX:+PrintCommandLineFlags"
        - name: "GET_JENKINS_IO_STAGING"
          value: "/var/www/get.jenkins.io.staging"
        - name: "PKG_JENKINS_IO_STAGING"
          value: "/var/www/pkg.jenkins.io.staging"
        - name: "GET_JENKINS_IO_PRODUCTION"
          value: "/var/www/get.jenkins.io.production"
        - name: "PKG_JENKINS_IO_PRODUCTION"
          value: "/var/www/pkg.jenkins.io.production"
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
        requests:
          memory: "1Gi"
          cpu: "1"
      securityContext:
        privileged: false
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: data-storage-jenkins-io
          mountPath: /var/www/get.jenkins.io.staging
          subPath: ./get.jenkins.io/mirrorbits-staging/
        - name: data-storage-jenkins-io
          mountPath: /var/www/get.jenkins.io.production
          subPath: ./get.jenkins.io/mirrorbits/
        - name: data-storage-jenkins-io
          mountPath: /var/www/pkg.jenkins.io.staging
          subPath: ./pkg.jenkins.io/staging/
        - name: data-storage-jenkins-io
          mountPath: /var/www/pkg.jenkins.io.production
          subPath: ./pkg.jenkins.io/production/
  volumes:
    - name: data-storage-jenkins-io
      persistentVolumeClaim:
        claimName: data-storage-jenkins-io
  nodeSelector:
    kubernetes.azure.com/agentpool: releasepool
    kubernetes.io/os: linux
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
    - key: "jenkins"
      operator: "Equal"
      value: "release.ci.jenkins.io"
      effect: "NoSchedule"
