apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    job: "package"
    #Following label is required by the workload identity process https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet#pod-labels
    azure.workload.identity/use: "true"
    #Following label is required by the NetworkPolicy managed by stable/jenkins helm chart and configured from jenkins-infra/charts
    jenkins/default-release-jenkins-agent: true
spec:
  serviceAccountName: release-ci-jenkins-io-agents
  containers:
  - image: jenkins/inbound-agent:3341.v0766d82b_dec0-4-jdk21-nanoserver-1809
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    env:
      - name: "JENKINS_JAVA_BIN"
        value: "C:/openjdk-21/bin/java"
      - name: "JENKINS_JAVA_OPTS"
        value: '"-XX:+PrintCommandLineFlags" --show-version'
    resources:
      limits:
        memory: "4Gi"
        cpu: "1"
      requests:
        memory: "4Gi"
        cpu: "1"
  - args:
      - -Command
      - Start-Sleep -s 2147483 # We must be sure that the process used by the container doesn't stop before the Jenkins job and second is not greater than 2147483
    command:
      - "powershell.exe"
    image: "mcr.microsoft.com/dotnet/framework/sdk:3.5"
    imagePullPolicy: "IfNotPresent"
    name: "dotnet"
    resources:
      limits:
        memory: "4Gi"
        cpu: "1"
      requests:
        memory: "4Gi"
        cpu: "1"
    securityContext:
      privileged: false
    tty: false
  nodeSelector:
    kubernetes.azure.com/agentpool: w2019
    kubernetes.io/os: windows
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
    - key: "jenkins"
      operator: "Equal"
      value: "release.ci.jenkins.io"
      effect: "NoSchedule"
