apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    job: "release"
spec:
  containers:
  - command:
    - "cat"
    env:
    - name: "HOME"
      value: "/home/jenkins/agent/workspace"
    image: "microsoft/azure-cli:2.0.59"
    imagePullPolicy: "IfNotPresent"
    name: "azure-cli"
    resources:
      limits:
        memory: "512Mi"
        cpu: "400m"
      requests:
        memory: "512Mi"
        cpu: "400m"
    securityContext:
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
    tty: true
  - command:
    - "cat"
    env:
    - name: "HOME"
      value: "/home/jenkins/agent/workspace"
    - name: "MAVEN_OPTS"
      value: "-Xmx8g -Xms8g"
    image: "maven:3.6.2-jdk-8"
    imagePullPolicy: "Always"
    name: "maven"
    resources:
      limits:
        memory: "16Gi"
        cpu: "4"
      requests:
        memory: "16Gi"
        cpu: "4"
    securityContext:
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
    tty: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: agentpool
            operator: In
            values:
            - highmemlinux
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
    - key: "profile"
      operator: "Equal"
      value: "highmem"
      effect: "NoSchedule"
  restartPolicy: "Never"
