apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job: "release"
    #Following label is required by the workload identity process https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet#pod-labels
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: release-ci-jenkins-io-agents
  containers:
    - name: jnlp
      image: jenkinsciinfra/packaging:8.2.12
      imagePullPolicy: "IfNotPresent"
      env:
        - name: "HOME"
          value: "/home/jenkins/agent/workspace"
        - name: "MAVEN_OPTS"
          value: "-Xmx8g -Xms8g"
        - name: "JENKINS_JAVA_BIN"
          value: "/opt/jdk-21/bin/java"
        - name: "JENKINS_JAVA_OPTS"
          value: "-XX:+PrintCommandLineFlags"
      resources:
        limits:
          memory: "16Gi"
          cpu: "4"
        requests:
          memory: "16Gi"
          cpu: "4"
      securityContext:
        privileged: false
        runAsUser: 1000
        runAsGroup: 1000
  restartPolicy: "Never"
  nodeSelector:
    kubernetes.azure.com/agentpool: releasepool
    kubernetes.io/os: linux
  tolerations:
    - key: "os"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
    - key: "jenkins"
      operator: "Equal"
      value: "release.ci.jenkins.io"
      effect: "NoSchedule"
