apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    job: "releasing"
spec:
  containers:
  - args:
    - "99d"
    command:
    - "sleep"
    env:
    - name: "HOME"
      value: "/home/jenkins"
    image: "microsoft/azure-cli:2.0.59"
    imagePullPolicy: "IfNotPresent"
    name: "azure-cli"
    resources:
      limits:
        memory: "512Mi"
        cpu: "400m"
      requests:
        memory: "512Mi"
        cpu: "400m"
    securityContext:
      privileged: false
    tty: false
  - args:
    - "99d"
    command:
    - "sleep"
    env:
    - name: "HOME"
      value: "/home/jenkins"
    - name: "MAVEN_OPTS"
      value: "-Xmx4g -Xms4g"
    image: "olblak/maven:3-jdk-8"
    imagePullPolicy: "Always"
    name: "maven"
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "4Gi"
        cpu: "2"
    securityContext:
      privileged: false
    tty: false
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
