#!/bin/bash
set -euo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

if [ $# -ne 1 ]; then
  echo "Usage: $1 <baseline_version>" >&2
  exit 1
fi

baseline=$1

# Make tagged commit part of the release branch
branch_name="stable-${baseline}"
# Use first child of release commit as branch point (`[maven-release-plugin] prepare for next development iteration`)
baseline_commit="$(git log --reverse --ancestry-path --pretty=%H jenkins-${baseline}..master | head -1)"
baseline_release_date="$(git show -s --format=%ct "${baseline_commit}")"
git checkout -b $branch_name "${baseline_commit}"

# Update versions
mvn -q versions:set-property -Dproperty=revision -DnewVersion=${baseline}.1

echo -Plts-release >> .mvn/maven.config

echo "$branch_name" > packaging-ref.txt

git add pom.xml .mvn/maven.config packaging-ref.txt
git commit -m "Towards ${baseline}.1"

# Create dedicated packaging branch
packaging="$(mktemp -d /tmp/jenkins-lts-rc-packaging-XXXXXXXX)"
trap "rm -rf '$packaging'" EXIT
git clone git@github.com:jenkinsci/packaging.git "$packaging"
pushd "$packaging"
# Use first child of release commit as branch point, using the datetime as there are no tags or formatted commits for packaging
baseline_packaging_commit="$(git log --until="${baseline_release_date}" --pretty=%H | head -1)"
git checkout -b "$branch_name" "${baseline_packaging_commit}"
git push -u origin "$branch_name"
popd

remote_name="$(git remote -v | awk '$2 == "git@github.com:jenkinsci/jenkins.git" && $3 == "(push)" {print $1}')"
cat <<EOF

Remember to:
    Push the branch
        $ git push --set-upstream ${remote_name} ${branch_name}
EOF

# Modify release profiles
release_repo="$(mktemp -d /tmp/jenkins-lts-rc-release-XXXXXXXX)"
trap "rm -rf '$release_repo'" EXIT
git clone git@github.com:jenkins-infra/release.git "$release_repo"
pushd "$release_repo"
# Use first child of release commit as branch point, using the datetime as there are no tags or formatted commits for jenkins-infra/release
baseline_infra_commit="$(git log --until="${baseline_release_date}" --pretty=%H | head -1)"
git checkout -b "$branch_name" "${baseline_infra_commit}"

sed -i'' -e "s/PACKAGING_GIT_BRANCH      = 'master'/PACKAGING_GIT_BRANCH      = '${branch_name}'/g" Jenkinsfile.d/core/package

sed -i'' -e "s/RELEASE_GIT_BRANCH=master/RELEASE_GIT_BRANCH=${branch_name}/g" profile.d/stable
echo "JENKINS_VERSION=${baseline}.1" >> profile.d/stable

git add Jenkinsfile.d/core/package profile.d/stable
git commit -m "Initiate ${baseline}.1"
git push origin "${branch_name}"
rm -f Jenkinsfile.d/core/package.bak
popd
